///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SWA_1_6_5_Release_Specific_Test_cases.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CommonRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0251c6f7-1d62-4d3d-8f75-6835a267e1ab")]
    public partial class CommonRepo : RepoGenBaseFolder
    {
        static CommonRepo instance = new CommonRepo();
        CommonRepoFolders.HttpsDevRahul0019291GuiSqlwaRenAppFolder _httpsdevrahul0019291guisqlwaren;
        CommonRepoFolders.IderaDashboardAppFolder _ideradashboard;
        CommonRepoFolders.CertificatePageAppFolder _certificatepage;
        CommonRepoFolders.PrivacyErrorGoogleChromeAppFolder _privacyerrorgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the CommonRepo element repository.
        /// </summary>
        [RepositoryFolder("0251c6f7-1d62-4d3d-8f75-6835a267e1ab")]
        public static CommonRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CommonRepo() 
            : base("CommonRepo", "/", null, 0, false, "0251c6f7-1d62-4d3d-8f75-6835a267e1ab", ".\\RepositoryImages\\CommonRepo0251c6f7.rximgres")
        {
            _httpsdevrahul0019291guisqlwaren = new CommonRepoFolders.HttpsDevRahul0019291GuiSqlwaRenAppFolder(this);
            _ideradashboard = new CommonRepoFolders.IderaDashboardAppFolder(this);
            _certificatepage = new CommonRepoFolders.CertificatePageAppFolder(this);
            _privacyerrorgooglechrome = new CommonRepoFolders.PrivacyErrorGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0251c6f7-1d62-4d3d-8f75-6835a267e1ab")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HttpsDevRahul0019291GuiSqlwaRen folder.
        /// </summary>
        [RepositoryFolder("c1345d5f-b2d6-4fb6-9480-cf907f01eab2")]
        public virtual CommonRepoFolders.HttpsDevRahul0019291GuiSqlwaRenAppFolder HttpsDevRahul0019291GuiSqlwaRen
        {
            get { return _httpsdevrahul0019291guisqlwaren; }
        }

        /// <summary>
        /// The IderaDashboard folder.
        /// </summary>
        [RepositoryFolder("d70f48c1-773a-494a-832f-be2f5959cb6f")]
        public virtual CommonRepoFolders.IderaDashboardAppFolder IderaDashboard
        {
            get { return _ideradashboard; }
        }

        /// <summary>
        /// The certificatePage folder.
        /// </summary>
        [RepositoryFolder("4463a818-cb8d-440d-8987-7a7c1dd007d0")]
        public virtual CommonRepoFolders.CertificatePageAppFolder certificatePage
        {
            get { return _certificatepage; }
        }

        /// <summary>
        /// The PrivacyErrorGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("af3b81c0-3113-4f1b-9d24-4215344fd6ca")]
        public virtual CommonRepoFolders.PrivacyErrorGoogleChromeAppFolder PrivacyErrorGoogleChrome
        {
            get { return _privacyerrorgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CommonRepoFolders
    {
        /// <summary>
        /// The HttpsDevRahul0019291GuiSqlwaRenAppFolder folder.
        /// </summary>
        [RepositoryFolder("c1345d5f-b2d6-4fb6-9480-cf907f01eab2")]
        public partial class HttpsDevRahul0019291GuiSqlwaRenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ataghashqtempInfo;

            /// <summary>
            /// Creates a new HttpsDevRahul0019291GuiSqlwaRen  folder.
            /// </summary>
            public HttpsDevRahul0019291GuiSqlwaRenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsDevRahul0019291GuiSqlwaRen", "/dom[@domain='dev-rahul-001:9291']", parentFolder, 30000, null, false, "c1345d5f-b2d6-4fb6-9480-cf907f01eab2", "")
            {
                _ataghashqtempInfo = new RepoItemInfo(this, "ATagHashqtemp", ".//iframe[#'iSeYn2']//table[#'topAccessObjectsDataTable']//a[@innertext='#qtemp']", 30000, null, "aa0dcd4d-84d2-4833-a4df-58dfee9cf499");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1345d5f-b2d6-4fb6-9480-cf907f01eab2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1345d5f-b2d6-4fb6-9480-cf907f01eab2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagHashqtemp item.
            /// </summary>
            [RepositoryItem("aa0dcd4d-84d2-4833-a4df-58dfee9cf499")]
            public virtual Ranorex.ATag ATagHashqtemp
            {
                get
                {
                    return _ataghashqtempInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagHashqtemp item info.
            /// </summary>
            [RepositoryItemInfo("aa0dcd4d-84d2-4833-a4df-58dfee9cf499")]
            public virtual RepoItemInfo ATagHashqtempInfo
            {
                get
                {
                    return _ataghashqtempInfo;
                }
            }
        }

        /// <summary>
        /// The IderaDashboardAppFolder folder.
        /// </summary>
        [RepositoryFolder("d70f48c1-773a-494a-832f-be2f5959cb6f")]
        public partial class IderaDashboardAppFolder : RepoGenBaseFolder
        {
            CommonRepoFolders.BC2Un2Folder _bc2un2;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _loginscreenInfo;
            RepoItemInfo _dashboardiconInfo;
            RepoItemInfo _dashboardmenuitemInfo;
            RepoItemInfo _swaitemdashboardInfo;
            RepoItemInfo _authnameInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _m82u80Info;

            /// <summary>
            /// Creates a new IderaDashboard  folder.
            /// </summary>
            public IderaDashboardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IderaDashboard", "/dom[@domain='localhost:9291']", parentFolder, 30000, null, false, "d70f48c1-773a-494a-832f-be2f5959cb6f", "")
            {
                _bc2un2 = new CommonRepoFolders.BC2Un2Folder(this);
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[@placeholder='Domain\\Username Credentials']", 30000, null, "1bb90905-bb3c-4eaa-b3a9-ce40073e9c8a");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[@placeholder='Password']", 30000, null, "1d009dd8-900e-49a9-90ff-e67e7c1c0675");
                _submitbuttonInfo = new RepoItemInfo(this, "submitButton", ".//button[@innertext='LOG IN']", 30000, null, "63843c56-f0c9-40cf-9c37-ed2c2398e120");
                _loginscreenInfo = new RepoItemInfo(this, "LoginScreen", ".//div[@class='login-panel z-vlayout']", 30000, null, "8a942af6-c8f7-46d5-afa4-d7e080590be6");
                _dashboardiconInfo = new RepoItemInfo(this, "dashBoardIcon", ".//span[@class='icon-menu-white icon-product-menu z-span']", 30000, null, "89d30cfa-945a-4717-b962-a79787a69e2b");
                _dashboardmenuitemInfo = new RepoItemInfo(this, "DashBoardMenuItem", ".//div[@class='product-listbox-body']", 30000, null, "d1a065be-4eaf-4e14-a61d-437c126aaaf9");
                _swaitemdashboardInfo = new RepoItemInfo(this, "swaItemDashBoard", ".//span[@innertext='SQLWorkloadAnalysis']", 30000, null, "c83a78a7-b240-4d71-a5d9-355a8547505b");
                _authnameInfo = new RepoItemInfo(this, "AuthName", ".//button[@innertext='simpsons\\administrator ']", 30000, null, "5f322d58-0eb5-4e26-9dd9-0824fa4b873c");
                _logoutInfo = new RepoItemInfo(this, "logOut", ".//a[@innertext=' Log Out']", 30000, null, "73c8bf2a-e6f6-424a-91bc-c5b8be5b8607");
                _m82u80Info = new RepoItemInfo(this, "M82U80", ".//span[@innertext='The user name or password you entered isn''t correct or you do not have permissions to any product. Contact your administrator to make sure you have permission to access the Idera Dashboard.']", 30000, null, "37ea4cd9-1674-4067-8daa-e9b5dd406cd1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d70f48c1-773a-494a-832f-be2f5959cb6f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d70f48c1-773a-494a-832f-be2f5959cb6f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("1bb90905-bb3c-4eaa-b3a9-ce40073e9c8a")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("1bb90905-bb3c-4eaa-b3a9-ce40073e9c8a")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("1d009dd8-900e-49a9-90ff-e67e7c1c0675")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("1d009dd8-900e-49a9-90ff-e67e7c1c0675")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The submitButton item.
            /// </summary>
            [RepositoryItem("63843c56-f0c9-40cf-9c37-ed2c2398e120")]
            public virtual Ranorex.ButtonTag submitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The submitButton item info.
            /// </summary>
            [RepositoryItemInfo("63843c56-f0c9-40cf-9c37-ed2c2398e120")]
            public virtual RepoItemInfo submitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The LoginScreen item.
            /// </summary>
            [RepositoryItem("8a942af6-c8f7-46d5-afa4-d7e080590be6")]
            public virtual Ranorex.DivTag LoginScreen
            {
                get
                {
                    return _loginscreenInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginScreen item info.
            /// </summary>
            [RepositoryItemInfo("8a942af6-c8f7-46d5-afa4-d7e080590be6")]
            public virtual RepoItemInfo LoginScreenInfo
            {
                get
                {
                    return _loginscreenInfo;
                }
            }

            /// <summary>
            /// The dashBoardIcon item.
            /// </summary>
            [RepositoryItem("89d30cfa-945a-4717-b962-a79787a69e2b")]
            public virtual Ranorex.SpanTag dashBoardIcon
            {
                get
                {
                    return _dashboardiconInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The dashBoardIcon item info.
            /// </summary>
            [RepositoryItemInfo("89d30cfa-945a-4717-b962-a79787a69e2b")]
            public virtual RepoItemInfo dashBoardIconInfo
            {
                get
                {
                    return _dashboardiconInfo;
                }
            }

            /// <summary>
            /// The DashBoardMenuItem item.
            /// </summary>
            [RepositoryItem("d1a065be-4eaf-4e14-a61d-437c126aaaf9")]
            public virtual Ranorex.DivTag DashBoardMenuItem
            {
                get
                {
                    return _dashboardmenuitemInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DashBoardMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("d1a065be-4eaf-4e14-a61d-437c126aaaf9")]
            public virtual RepoItemInfo DashBoardMenuItemInfo
            {
                get
                {
                    return _dashboardmenuitemInfo;
                }
            }

            /// <summary>
            /// The swaItemDashBoard item.
            /// </summary>
            [RepositoryItem("c83a78a7-b240-4d71-a5d9-355a8547505b")]
            public virtual Ranorex.SpanTag swaItemDashBoard
            {
                get
                {
                    return _swaitemdashboardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The swaItemDashBoard item info.
            /// </summary>
            [RepositoryItemInfo("c83a78a7-b240-4d71-a5d9-355a8547505b")]
            public virtual RepoItemInfo swaItemDashBoardInfo
            {
                get
                {
                    return _swaitemdashboardInfo;
                }
            }

            /// <summary>
            /// The AuthName item.
            /// </summary>
            [RepositoryItem("5f322d58-0eb5-4e26-9dd9-0824fa4b873c")]
            public virtual Ranorex.ButtonTag AuthName
            {
                get
                {
                    return _authnameInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AuthName item info.
            /// </summary>
            [RepositoryItemInfo("5f322d58-0eb5-4e26-9dd9-0824fa4b873c")]
            public virtual RepoItemInfo AuthNameInfo
            {
                get
                {
                    return _authnameInfo;
                }
            }

            /// <summary>
            /// The logOut item.
            /// </summary>
            [RepositoryItem("73c8bf2a-e6f6-424a-91bc-c5b8be5b8607")]
            public virtual Ranorex.ATag logOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The logOut item info.
            /// </summary>
            [RepositoryItemInfo("73c8bf2a-e6f6-424a-91bc-c5b8be5b8607")]
            public virtual RepoItemInfo logOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The M82U80 item.
            /// </summary>
            [RepositoryItem("37ea4cd9-1674-4067-8daa-e9b5dd406cd1")]
            public virtual Ranorex.SpanTag M82U80
            {
                get
                {
                    return _m82u80Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The M82U80 item info.
            /// </summary>
            [RepositoryItemInfo("37ea4cd9-1674-4067-8daa-e9b5dd406cd1")]
            public virtual RepoItemInfo M82U80Info
            {
                get
                {
                    return _m82u80Info;
                }
            }

            /// <summary>
            /// The BC2Un2 folder.
            /// </summary>
            [RepositoryFolder("11396b79-6127-4f74-8993-f96c1fd86f6e")]
            public virtual CommonRepoFolders.BC2Un2Folder BC2Un2
            {
                get { return _bc2un2; }
            }
        }

        /// <summary>
        /// The BC2Un2Folder folder.
        /// </summary>
        [RepositoryFolder("11396b79-6127-4f74-8993-f96c1fd86f6e")]
        public partial class BC2Un2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _instancesleftdatatableInfo;
            RepoItemInfo _topstatementsInfo;
            RepoItemInfo _topstatementsdatatableInfo;
            RepoItemInfo _entityoverviewdatatable1Info;
            RepoItemInfo _oswaitInfo;
            RepoItemInfo _topaccessobjectsInfo;
            RepoItemInfo _leftcomponentInfo;
            RepoItemInfo _contentInfo;
            RepoItemInfo _topaccessobjectsdatatableInfo;
            RepoItemInfo _overlappingpopupInfo;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _timedelayselectionInfo;
            RepoItemInfo _topstatementsdatatable1Info;
            RepoItemInfo _btnbackInfo;
            RepoItemInfo _cpuutilizationovertimeInfo;
            RepoItemInfo _admintabInfo;
            RepoItemInfo _machinesInfo;
            RepoItemInfo _topmachinesInfo;
            RepoItemInfo _topprogramsInfo;
            RepoItemInfo _topprogramsdatatableInfo;
            RepoItemInfo _sqlstatementfullInfo;
            RepoItemInfo _usersdatatableInfo;
            RepoItemInfo _toploginsInfo;
            RepoItemInfo _widgetcontentInfo;
            RepoItemInfo _lockedstatementsInfo;
            RepoItemInfo _widgetcontent1Info;
            RepoItemInfo _topstatementsleftdatatableInfo;
            RepoItemInfo _topstatementsleftdatatable1Info;
            RepoItemInfo _entityoverviewdatatableInfo;
            RepoItemInfo _managesqlserverinstancesInfo;
            RepoItemInfo _manageinstanceInfo;
            RepoItemInfo _removeinstancebtnInfo;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _spantaghomeInfo;
            RepoItemInfo _addsqlserverinstanceInfo;
            RepoItemInfo _administrationInfo;
            RepoItemInfo _managelicenseInfo;
            RepoItemInfo _licensekeyInfo;
            RepoItemInfo _applybuttonInfo;
            RepoItemInfo _machinesdatatableInfo;

            /// <summary>
            /// Creates a new BC2Un2  folder.
            /// </summary>
            public BC2Un2Folder(RepoGenBaseFolder parentFolder) :
                    base("BC2Un2", ".//iframe[1]", parentFolder, 30000, null, false, "11396b79-6127-4f74-8993-f96c1fd86f6e", "")
            {
                _instancesleftdatatableInfo = new RepoItemInfo(this, "InstancesLeftDataTable", ".//table[#'instancesLeftDataTable']/tbody/?/?/td[@innertext='DEV-RAHUL-001']", 30000, null, "107a014d-2dee-4ecc-ad41-8594763ec00c");
                _topstatementsInfo = new RepoItemInfo(this, "TopStatements", ".//table[#'topStatementsDataTable']/tbody", 30000, null, "b3ec8141-a336-4603-8ac2-85f96bf80936");
                _topstatementsdatatableInfo = new RepoItemInfo(this, "TopStatementsDataTable", ".//table[#'topStatementsDataTable']/tbody", 30000, null, "2010f881-04ea-4c27-ab13-5eb9f7b8a654");
                _entityoverviewdatatable1Info = new RepoItemInfo(this, "EntityOverviewDataTable1", ".//table[#'entityOverviewDataTable']/tbody/?/td[@title~'Analyze statements experiencing OS waits']", 30000, null, "8c761499-8c97-474f-8c62-56f2d81bb39e");
                _oswaitInfo = new RepoItemInfo(this, "OSWait", ".//table[#'entityOverviewDataTable']//a[@innertext='OS Wait']", 30000, null, "3d9defd9-eabe-4ef7-ba04-2709ce73cd33");
                _topaccessobjectsInfo = new RepoItemInfo(this, "TopAccessObjects", ".//table[#'topAccessObjectsDataTable']", 30000, null, "98ad7863-d354-46f2-a778-92786403bee4");
                _leftcomponentInfo = new RepoItemInfo(this, "LeftComponent", ".//table[#'topTablesLeftDataTable']/tbody", 30000, null, "a22feb6f-dd59-4786-b659-217f1b2817cf");
                _contentInfo = new RepoItemInfo(this, "Content", ".//div[#'content']", 30000, null, "198884fd-5e3c-4eb8-9a68-3148b3768f08");
                _topaccessobjectsdatatableInfo = new RepoItemInfo(this, "TopAccessObjectsDataTable", ".//table[#'topAccessObjectsDataTable']/tbody", 30000, null, "0bbc78f5-4859-4a68-8449-51c00d1e32c6");
                _overlappingpopupInfo = new RepoItemInfo(this, "OverlappingPopup", ".//div[#'overlappingPopup']", 30000, null, "d08e9a3d-c037-4dae-9dd5-d336a90534e5");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//button[#'okButton']", 30000, null, "100f378b-517d-46a4-9602-d551bde0a7a4");
                _timedelayselectionInfo = new RepoItemInfo(this, "timeDelaySelection", ".//table[#'timeframe_buttons']/?/?/tr", 30000, null, "8a39e832-aaf6-460b-8b2c-85dc6fe16468");
                _topstatementsdatatable1Info = new RepoItemInfo(this, "TopStatementsDataTable1", ".//table[#'topStatementsDataTable']/tbody", 30000, null, "a3e734be-079e-4582-960e-1e8875df2bad");
                _btnbackInfo = new RepoItemInfo(this, "BtnBack", ".//button[#'btnBack']", 30000, null, "4ed611ec-a573-46d7-acca-8e7919ce17c0");
                _cpuutilizationovertimeInfo = new RepoItemInfo(this, "CpuUtilizationOverTime", ".//li[#'cpuUtilizationOverTime']", 30000, null, "b86df169-39d9-44b3-a364-f6c2d8253b64");
                _admintabInfo = new RepoItemInfo(this, "AdminTab", ".//div[#'mostOuterDiv']/?/?/ul/li[2]/a", 30000, null, "b6482eee-151b-418a-8778-e8ac56d290ec");
                _machinesInfo = new RepoItemInfo(this, "Machines", ".//li[#'machines']", 30000, null, "b1ec6add-a5b5-4d2a-b2a9-27a11660a98f");
                _topmachinesInfo = new RepoItemInfo(this, "topMachines", ".//table[#'machinesDataTable']/tbody", 30000, null, "51c5fcec-c81d-454c-9ec9-dab32060ae7c");
                _topprogramsInfo = new RepoItemInfo(this, "TopPrograms", ".//li[#'topPrograms']", 30000, null, "4743a66e-c0ee-4b04-8d63-848c9f8df29e");
                _topprogramsdatatableInfo = new RepoItemInfo(this, "TopProgramsDataTable", ".//table[#'topProgramsDataTable']/tbody", 30000, null, "f9575270-3f7c-415a-bafe-60a86af028a3");
                _sqlstatementfullInfo = new RepoItemInfo(this, "SQLStatementFull", ".//li[#'statementFullText']/div[3]//pre", 30000, null, "f1264fd5-e5f9-4edd-ae97-6b7718665fcc");
                _usersdatatableInfo = new RepoItemInfo(this, "UsersDataTable", ".//table[#'usersDataTable']/tbody", 30000, null, "e2dee0df-4fe1-47b8-abad-8a483c19991a");
                _toploginsInfo = new RepoItemInfo(this, "TopLogins", ".//table[#'usersDataTable']/tbody", 30000, null, "f2fcd047-1c67-4cd3-94b0-bc767c06b587");
                _widgetcontentInfo = new RepoItemInfo(this, "WidgetContent", ".//li[#'machines']/div[3]", 30000, null, "cdddbf26-0eb7-46e2-8953-3af06f4850e2");
                _lockedstatementsInfo = new RepoItemInfo(this, "LockedStatements", ".//li[#'lockedStatements']", 30000, null, "8ebe5060-db32-4387-a8cf-d1c95b21f04a");
                _widgetcontent1Info = new RepoItemInfo(this, "WidgetContent1", ".//tr[#'lockedStatements1']/td[2]/?/?/a", 30000, null, "af0aec4e-3bf1-400c-8123-9bd8adbb8248");
                _topstatementsleftdatatableInfo = new RepoItemInfo(this, "TopStatementsLeftDataTable", ".//table[#'topStatementsLeftDataTable']/tbody/tr", 30000, null, "587f3ec6-9f00-412b-8be0-7e261264b3d5");
                _topstatementsleftdatatable1Info = new RepoItemInfo(this, "TopStatementsLeftDataTable1", ".//table[#'topStatementsLeftDataTable']/tbody", 30000, null, "c47ffa8f-fa8f-434d-95ee-f0a332313228");
                _entityoverviewdatatableInfo = new RepoItemInfo(this, "EntityOverviewDataTable", ".//table[#'entityOverviewDataTable']/tbody", 30000, null, "d09bba2e-68ac-4f58-9129-8e34a2955dba");
                _managesqlserverinstancesInfo = new RepoItemInfo(this, "ManageSQLServerInstances", ".//a[#'manageCheck']/span[@innertext~'^Manage\\ SQL\\ Server\\ Instanc']", 30000, null, "763eaf8d-d085-46e0-86be-2f36110c124f");
                _manageinstanceInfo = new RepoItemInfo(this, "ManageInstance", ".//div[#'content']/div[2]/div[4]/div[3]/div/table/tbody", 30000, null, "3dd8e0d0-97ce-4fd2-b9b3-0fc914e598a2");
                _removeinstancebtnInfo = new RepoItemInfo(this, "RemoveInstancebtn", ".//input[#'removeInstancebtn']", 30000, null, "58f0c2e7-362c-4df1-8250-9d9f59fef5f8");
                _buttonInfo = new RepoItemInfo(this, "Button", ".//div[#'content']//ul/?/?/input[@value='CLOSE']", 30000, null, "0277f66a-79a1-42a0-9704-bd0705627eed");
                _spantaghomeInfo = new RepoItemInfo(this, "SpanTagHOME", ".//div[#'mostOuterDiv']/div[1]/ul//span[@innertext=' HOME']", 30000, null, "390b1fe2-063f-4444-9863-83a18cd96aa5");
                _addsqlserverinstanceInfo = new RepoItemInfo(this, "AddSQLServerInstance", ".//a[#'addCheck']/span[@innertext='Add SQL Server Instance']", 30000, null, "fb276867-4aa7-4d3f-adba-dfae403b459e");
                _administrationInfo = new RepoItemInfo(this, "ADMINISTRATION", ".//div[#'mostOuterDiv']/?/?/ul//span[@innertext='ADMINISTRATION']", 30000, null, "d582ef78-053a-4dc0-b0c3-e9b3199d4b00");
                _managelicenseInfo = new RepoItemInfo(this, "ManageLicense", ".//div[#'adminContainer']//span[@innertext='Manage License']", 30000, null, "bc82cf4e-b763-4b49-9acf-087f8dc40d95");
                _licensekeyInfo = new RepoItemInfo(this, "LicenseKey", ".//input[#'liKey']", 30000, null, "64868636-5f92-4a7c-a51d-257ac23eb2db");
                _applybuttonInfo = new RepoItemInfo(this, "ApplyButton", ".//div[#'content']/div[2]/div[1]/div[2]/table[2]//input[@type='button']", 30000, null, "c21d8c26-76a1-41b5-8769-249fa9848d53");
                _machinesdatatableInfo = new RepoItemInfo(this, "MachinesDataTable", ".//table[#'machinesDataTable']", 30000, null, "12368075-a573-4c36-a0d5-944e5b805c72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("11396b79-6127-4f74-8993-f96c1fd86f6e")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("11396b79-6127-4f74-8993-f96c1fd86f6e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InstancesLeftDataTable item.
            /// </summary>
            [RepositoryItem("107a014d-2dee-4ecc-ad41-8594763ec00c")]
            public virtual Ranorex.TdTag InstancesLeftDataTable
            {
                get
                {
                    return _instancesleftdatatableInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The InstancesLeftDataTable item info.
            /// </summary>
            [RepositoryItemInfo("107a014d-2dee-4ecc-ad41-8594763ec00c")]
            public virtual RepoItemInfo InstancesLeftDataTableInfo
            {
                get
                {
                    return _instancesleftdatatableInfo;
                }
            }

            /// <summary>
            /// The TopStatements item.
            /// </summary>
            [RepositoryItem("b3ec8141-a336-4603-8ac2-85f96bf80936")]
            public virtual Ranorex.TBodyTag TopStatements
            {
                get
                {
                    return _topstatementsInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopStatements item info.
            /// </summary>
            [RepositoryItemInfo("b3ec8141-a336-4603-8ac2-85f96bf80936")]
            public virtual RepoItemInfo TopStatementsInfo
            {
                get
                {
                    return _topstatementsInfo;
                }
            }

            /// <summary>
            /// The TopStatementsDataTable item.
            /// </summary>
            [RepositoryItem("2010f881-04ea-4c27-ab13-5eb9f7b8a654")]
            public virtual Ranorex.TBodyTag TopStatementsDataTable
            {
                get
                {
                    return _topstatementsdatatableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopStatementsDataTable item info.
            /// </summary>
            [RepositoryItemInfo("2010f881-04ea-4c27-ab13-5eb9f7b8a654")]
            public virtual RepoItemInfo TopStatementsDataTableInfo
            {
                get
                {
                    return _topstatementsdatatableInfo;
                }
            }

            /// <summary>
            /// The EntityOverviewDataTable1 item.
            /// </summary>
            [RepositoryItem("8c761499-8c97-474f-8c62-56f2d81bb39e")]
            public virtual Ranorex.TdTag EntityOverviewDataTable1
            {
                get
                {
                    return _entityoverviewdatatable1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The EntityOverviewDataTable1 item info.
            /// </summary>
            [RepositoryItemInfo("8c761499-8c97-474f-8c62-56f2d81bb39e")]
            public virtual RepoItemInfo EntityOverviewDataTable1Info
            {
                get
                {
                    return _entityoverviewdatatable1Info;
                }
            }

            /// <summary>
            /// The OSWait item.
            /// </summary>
            [RepositoryItem("3d9defd9-eabe-4ef7-ba04-2709ce73cd33")]
            public virtual Ranorex.ATag OSWait
            {
                get
                {
                    return _oswaitInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OSWait item info.
            /// </summary>
            [RepositoryItemInfo("3d9defd9-eabe-4ef7-ba04-2709ce73cd33")]
            public virtual RepoItemInfo OSWaitInfo
            {
                get
                {
                    return _oswaitInfo;
                }
            }

            /// <summary>
            /// The TopAccessObjects item.
            /// </summary>
            [RepositoryItem("98ad7863-d354-46f2-a778-92786403bee4")]
            public virtual Ranorex.Table TopAccessObjects
            {
                get
                {
                    return _topaccessobjectsInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The TopAccessObjects item info.
            /// </summary>
            [RepositoryItemInfo("98ad7863-d354-46f2-a778-92786403bee4")]
            public virtual RepoItemInfo TopAccessObjectsInfo
            {
                get
                {
                    return _topaccessobjectsInfo;
                }
            }

            /// <summary>
            /// The LeftComponent item.
            /// </summary>
            [RepositoryItem("a22feb6f-dd59-4786-b659-217f1b2817cf")]
            public virtual Ranorex.TBodyTag LeftComponent
            {
                get
                {
                    return _leftcomponentInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The LeftComponent item info.
            /// </summary>
            [RepositoryItemInfo("a22feb6f-dd59-4786-b659-217f1b2817cf")]
            public virtual RepoItemInfo LeftComponentInfo
            {
                get
                {
                    return _leftcomponentInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("198884fd-5e3c-4eb8-9a68-3148b3768f08")]
            public virtual Ranorex.DivTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("198884fd-5e3c-4eb8-9a68-3148b3768f08")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The TopAccessObjectsDataTable item.
            /// </summary>
            [RepositoryItem("0bbc78f5-4859-4a68-8449-51c00d1e32c6")]
            public virtual Ranorex.TBodyTag TopAccessObjectsDataTable
            {
                get
                {
                    return _topaccessobjectsdatatableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopAccessObjectsDataTable item info.
            /// </summary>
            [RepositoryItemInfo("0bbc78f5-4859-4a68-8449-51c00d1e32c6")]
            public virtual RepoItemInfo TopAccessObjectsDataTableInfo
            {
                get
                {
                    return _topaccessobjectsdatatableInfo;
                }
            }

            /// <summary>
            /// The OverlappingPopup item.
            /// </summary>
            [RepositoryItem("d08e9a3d-c037-4dae-9dd5-d336a90534e5")]
            public virtual Ranorex.DivTag OverlappingPopup
            {
                get
                {
                    return _overlappingpopupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The OverlappingPopup item info.
            /// </summary>
            [RepositoryItemInfo("d08e9a3d-c037-4dae-9dd5-d336a90534e5")]
            public virtual RepoItemInfo OverlappingPopupInfo
            {
                get
                {
                    return _overlappingpopupInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("100f378b-517d-46a4-9602-d551bde0a7a4")]
            public virtual Ranorex.ButtonTag OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("100f378b-517d-46a4-9602-d551bde0a7a4")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The timeDelaySelection item.
            /// </summary>
            [RepositoryItem("8a39e832-aaf6-460b-8b2c-85dc6fe16468")]
            public virtual Ranorex.TrTag timeDelaySelection
            {
                get
                {
                    return _timedelayselectionInfo.CreateAdapter<Ranorex.TrTag>(true);
                }
            }

            /// <summary>
            /// The timeDelaySelection item info.
            /// </summary>
            [RepositoryItemInfo("8a39e832-aaf6-460b-8b2c-85dc6fe16468")]
            public virtual RepoItemInfo timeDelaySelectionInfo
            {
                get
                {
                    return _timedelayselectionInfo;
                }
            }

            /// <summary>
            /// The TopStatementsDataTable1 item.
            /// </summary>
            [RepositoryItem("a3e734be-079e-4582-960e-1e8875df2bad")]
            public virtual Ranorex.TBodyTag TopStatementsDataTable1
            {
                get
                {
                    return _topstatementsdatatable1Info.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopStatementsDataTable1 item info.
            /// </summary>
            [RepositoryItemInfo("a3e734be-079e-4582-960e-1e8875df2bad")]
            public virtual RepoItemInfo TopStatementsDataTable1Info
            {
                get
                {
                    return _topstatementsdatatable1Info;
                }
            }

            /// <summary>
            /// The BtnBack item.
            /// </summary>
            [RepositoryItem("4ed611ec-a573-46d7-acca-8e7919ce17c0")]
            public virtual Ranorex.ButtonTag BtnBack
            {
                get
                {
                    return _btnbackInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnBack item info.
            /// </summary>
            [RepositoryItemInfo("4ed611ec-a573-46d7-acca-8e7919ce17c0")]
            public virtual RepoItemInfo BtnBackInfo
            {
                get
                {
                    return _btnbackInfo;
                }
            }

            /// <summary>
            /// The CpuUtilizationOverTime item.
            /// </summary>
            [RepositoryItem("b86df169-39d9-44b3-a364-f6c2d8253b64")]
            public virtual Ranorex.LiTag CpuUtilizationOverTime
            {
                get
                {
                    return _cpuutilizationovertimeInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The CpuUtilizationOverTime item info.
            /// </summary>
            [RepositoryItemInfo("b86df169-39d9-44b3-a364-f6c2d8253b64")]
            public virtual RepoItemInfo CpuUtilizationOverTimeInfo
            {
                get
                {
                    return _cpuutilizationovertimeInfo;
                }
            }

            /// <summary>
            /// The AdminTab item.
            /// </summary>
            [RepositoryItem("b6482eee-151b-418a-8778-e8ac56d290ec")]
            public virtual Ranorex.ATag AdminTab
            {
                get
                {
                    return _admintabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AdminTab item info.
            /// </summary>
            [RepositoryItemInfo("b6482eee-151b-418a-8778-e8ac56d290ec")]
            public virtual RepoItemInfo AdminTabInfo
            {
                get
                {
                    return _admintabInfo;
                }
            }

            /// <summary>
            /// The Machines item.
            /// </summary>
            [RepositoryItem("b1ec6add-a5b5-4d2a-b2a9-27a11660a98f")]
            public virtual Ranorex.LiTag Machines
            {
                get
                {
                    return _machinesInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Machines item info.
            /// </summary>
            [RepositoryItemInfo("b1ec6add-a5b5-4d2a-b2a9-27a11660a98f")]
            public virtual RepoItemInfo MachinesInfo
            {
                get
                {
                    return _machinesInfo;
                }
            }

            /// <summary>
            /// The topMachines item.
            /// </summary>
            [RepositoryItem("51c5fcec-c81d-454c-9ec9-dab32060ae7c")]
            public virtual Ranorex.TBodyTag topMachines
            {
                get
                {
                    return _topmachinesInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The topMachines item info.
            /// </summary>
            [RepositoryItemInfo("51c5fcec-c81d-454c-9ec9-dab32060ae7c")]
            public virtual RepoItemInfo topMachinesInfo
            {
                get
                {
                    return _topmachinesInfo;
                }
            }

            /// <summary>
            /// The TopPrograms item.
            /// </summary>
            [RepositoryItem("4743a66e-c0ee-4b04-8d63-848c9f8df29e")]
            public virtual Ranorex.LiTag TopPrograms
            {
                get
                {
                    return _topprogramsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The TopPrograms item info.
            /// </summary>
            [RepositoryItemInfo("4743a66e-c0ee-4b04-8d63-848c9f8df29e")]
            public virtual RepoItemInfo TopProgramsInfo
            {
                get
                {
                    return _topprogramsInfo;
                }
            }

            /// <summary>
            /// The TopProgramsDataTable item.
            /// </summary>
            [RepositoryItem("f9575270-3f7c-415a-bafe-60a86af028a3")]
            public virtual Ranorex.TBodyTag TopProgramsDataTable
            {
                get
                {
                    return _topprogramsdatatableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopProgramsDataTable item info.
            /// </summary>
            [RepositoryItemInfo("f9575270-3f7c-415a-bafe-60a86af028a3")]
            public virtual RepoItemInfo TopProgramsDataTableInfo
            {
                get
                {
                    return _topprogramsdatatableInfo;
                }
            }

            /// <summary>
            /// The SQLStatementFull item.
            /// </summary>
            [RepositoryItem("f1264fd5-e5f9-4edd-ae97-6b7718665fcc")]
            public virtual Ranorex.PreTag SQLStatementFull
            {
                get
                {
                    return _sqlstatementfullInfo.CreateAdapter<Ranorex.PreTag>(true);
                }
            }

            /// <summary>
            /// The SQLStatementFull item info.
            /// </summary>
            [RepositoryItemInfo("f1264fd5-e5f9-4edd-ae97-6b7718665fcc")]
            public virtual RepoItemInfo SQLStatementFullInfo
            {
                get
                {
                    return _sqlstatementfullInfo;
                }
            }

            /// <summary>
            /// The UsersDataTable item.
            /// </summary>
            [RepositoryItem("e2dee0df-4fe1-47b8-abad-8a483c19991a")]
            public virtual Ranorex.TBodyTag UsersDataTable
            {
                get
                {
                    return _usersdatatableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The UsersDataTable item info.
            /// </summary>
            [RepositoryItemInfo("e2dee0df-4fe1-47b8-abad-8a483c19991a")]
            public virtual RepoItemInfo UsersDataTableInfo
            {
                get
                {
                    return _usersdatatableInfo;
                }
            }

            /// <summary>
            /// The TopLogins item.
            /// </summary>
            [RepositoryItem("f2fcd047-1c67-4cd3-94b0-bc767c06b587")]
            public virtual Ranorex.TBodyTag TopLogins
            {
                get
                {
                    return _toploginsInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopLogins item info.
            /// </summary>
            [RepositoryItemInfo("f2fcd047-1c67-4cd3-94b0-bc767c06b587")]
            public virtual RepoItemInfo TopLoginsInfo
            {
                get
                {
                    return _toploginsInfo;
                }
            }

            /// <summary>
            /// The WidgetContent item.
            /// </summary>
            [RepositoryItem("cdddbf26-0eb7-46e2-8953-3af06f4850e2")]
            public virtual Ranorex.DivTag WidgetContent
            {
                get
                {
                    return _widgetcontentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The WidgetContent item info.
            /// </summary>
            [RepositoryItemInfo("cdddbf26-0eb7-46e2-8953-3af06f4850e2")]
            public virtual RepoItemInfo WidgetContentInfo
            {
                get
                {
                    return _widgetcontentInfo;
                }
            }

            /// <summary>
            /// The LockedStatements item.
            /// </summary>
            [RepositoryItem("8ebe5060-db32-4387-a8cf-d1c95b21f04a")]
            public virtual Ranorex.LiTag LockedStatements
            {
                get
                {
                    return _lockedstatementsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LockedStatements item info.
            /// </summary>
            [RepositoryItemInfo("8ebe5060-db32-4387-a8cf-d1c95b21f04a")]
            public virtual RepoItemInfo LockedStatementsInfo
            {
                get
                {
                    return _lockedstatementsInfo;
                }
            }

            /// <summary>
            /// The WidgetContent1 item.
            /// </summary>
            [RepositoryItem("af0aec4e-3bf1-400c-8123-9bd8adbb8248")]
            public virtual Ranorex.ATag WidgetContent1
            {
                get
                {
                    return _widgetcontent1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The WidgetContent1 item info.
            /// </summary>
            [RepositoryItemInfo("af0aec4e-3bf1-400c-8123-9bd8adbb8248")]
            public virtual RepoItemInfo WidgetContent1Info
            {
                get
                {
                    return _widgetcontent1Info;
                }
            }

            /// <summary>
            /// The TopStatementsLeftDataTable item.
            /// </summary>
            [RepositoryItem("587f3ec6-9f00-412b-8be0-7e261264b3d5")]
            public virtual Ranorex.TrTag TopStatementsLeftDataTable
            {
                get
                {
                    return _topstatementsleftdatatableInfo.CreateAdapter<Ranorex.TrTag>(true);
                }
            }

            /// <summary>
            /// The TopStatementsLeftDataTable item info.
            /// </summary>
            [RepositoryItemInfo("587f3ec6-9f00-412b-8be0-7e261264b3d5")]
            public virtual RepoItemInfo TopStatementsLeftDataTableInfo
            {
                get
                {
                    return _topstatementsleftdatatableInfo;
                }
            }

            /// <summary>
            /// The TopStatementsLeftDataTable1 item.
            /// </summary>
            [RepositoryItem("c47ffa8f-fa8f-434d-95ee-f0a332313228")]
            public virtual Ranorex.TBodyTag TopStatementsLeftDataTable1
            {
                get
                {
                    return _topstatementsleftdatatable1Info.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The TopStatementsLeftDataTable1 item info.
            /// </summary>
            [RepositoryItemInfo("c47ffa8f-fa8f-434d-95ee-f0a332313228")]
            public virtual RepoItemInfo TopStatementsLeftDataTable1Info
            {
                get
                {
                    return _topstatementsleftdatatable1Info;
                }
            }

            /// <summary>
            /// The EntityOverviewDataTable item.
            /// </summary>
            [RepositoryItem("d09bba2e-68ac-4f58-9129-8e34a2955dba")]
            public virtual Ranorex.TBodyTag EntityOverviewDataTable
            {
                get
                {
                    return _entityoverviewdatatableInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The EntityOverviewDataTable item info.
            /// </summary>
            [RepositoryItemInfo("d09bba2e-68ac-4f58-9129-8e34a2955dba")]
            public virtual RepoItemInfo EntityOverviewDataTableInfo
            {
                get
                {
                    return _entityoverviewdatatableInfo;
                }
            }

            /// <summary>
            /// The ManageSQLServerInstances item.
            /// </summary>
            [RepositoryItem("763eaf8d-d085-46e0-86be-2f36110c124f")]
            public virtual Ranorex.SpanTag ManageSQLServerInstances
            {
                get
                {
                    return _managesqlserverinstancesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ManageSQLServerInstances item info.
            /// </summary>
            [RepositoryItemInfo("763eaf8d-d085-46e0-86be-2f36110c124f")]
            public virtual RepoItemInfo ManageSQLServerInstancesInfo
            {
                get
                {
                    return _managesqlserverinstancesInfo;
                }
            }

            /// <summary>
            /// The ManageInstance item.
            /// </summary>
            [RepositoryItem("3dd8e0d0-97ce-4fd2-b9b3-0fc914e598a2")]
            public virtual Ranorex.TBodyTag ManageInstance
            {
                get
                {
                    return _manageinstanceInfo.CreateAdapter<Ranorex.TBodyTag>(true);
                }
            }

            /// <summary>
            /// The ManageInstance item info.
            /// </summary>
            [RepositoryItemInfo("3dd8e0d0-97ce-4fd2-b9b3-0fc914e598a2")]
            public virtual RepoItemInfo ManageInstanceInfo
            {
                get
                {
                    return _manageinstanceInfo;
                }
            }

            /// <summary>
            /// The RemoveInstancebtn item.
            /// </summary>
            [RepositoryItem("58f0c2e7-362c-4df1-8250-9d9f59fef5f8")]
            public virtual Ranorex.InputTag RemoveInstancebtn
            {
                get
                {
                    return _removeinstancebtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RemoveInstancebtn item info.
            /// </summary>
            [RepositoryItemInfo("58f0c2e7-362c-4df1-8250-9d9f59fef5f8")]
            public virtual RepoItemInfo RemoveInstancebtnInfo
            {
                get
                {
                    return _removeinstancebtnInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("0277f66a-79a1-42a0-9704-bd0705627eed")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("0277f66a-79a1-42a0-9704-bd0705627eed")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The SpanTagHOME item.
            /// </summary>
            [RepositoryItem("390b1fe2-063f-4444-9863-83a18cd96aa5")]
            public virtual Ranorex.SpanTag SpanTagHOME
            {
                get
                {
                    return _spantaghomeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagHOME item info.
            /// </summary>
            [RepositoryItemInfo("390b1fe2-063f-4444-9863-83a18cd96aa5")]
            public virtual RepoItemInfo SpanTagHOMEInfo
            {
                get
                {
                    return _spantaghomeInfo;
                }
            }

            /// <summary>
            /// The AddSQLServerInstance item.
            /// </summary>
            [RepositoryItem("fb276867-4aa7-4d3f-adba-dfae403b459e")]
            public virtual Ranorex.SpanTag AddSQLServerInstance
            {
                get
                {
                    return _addsqlserverinstanceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddSQLServerInstance item info.
            /// </summary>
            [RepositoryItemInfo("fb276867-4aa7-4d3f-adba-dfae403b459e")]
            public virtual RepoItemInfo AddSQLServerInstanceInfo
            {
                get
                {
                    return _addsqlserverinstanceInfo;
                }
            }

            /// <summary>
            /// The ADMINISTRATION item.
            /// </summary>
            [RepositoryItem("d582ef78-053a-4dc0-b0c3-e9b3199d4b00")]
            public virtual Ranorex.SpanTag ADMINISTRATION
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ADMINISTRATION item info.
            /// </summary>
            [RepositoryItemInfo("d582ef78-053a-4dc0-b0c3-e9b3199d4b00")]
            public virtual RepoItemInfo ADMINISTRATIONInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The ManageLicense item.
            /// </summary>
            [RepositoryItem("bc82cf4e-b763-4b49-9acf-087f8dc40d95")]
            public virtual Ranorex.SpanTag ManageLicense
            {
                get
                {
                    return _managelicenseInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ManageLicense item info.
            /// </summary>
            [RepositoryItemInfo("bc82cf4e-b763-4b49-9acf-087f8dc40d95")]
            public virtual RepoItemInfo ManageLicenseInfo
            {
                get
                {
                    return _managelicenseInfo;
                }
            }

            /// <summary>
            /// The LicenseKey item.
            /// </summary>
            [RepositoryItem("64868636-5f92-4a7c-a51d-257ac23eb2db")]
            public virtual Ranorex.InputTag LicenseKey
            {
                get
                {
                    return _licensekeyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LicenseKey item info.
            /// </summary>
            [RepositoryItemInfo("64868636-5f92-4a7c-a51d-257ac23eb2db")]
            public virtual RepoItemInfo LicenseKeyInfo
            {
                get
                {
                    return _licensekeyInfo;
                }
            }

            /// <summary>
            /// The ApplyButton item.
            /// </summary>
            [RepositoryItem("c21d8c26-76a1-41b5-8769-249fa9848d53")]
            public virtual Ranorex.InputTag ApplyButton
            {
                get
                {
                    return _applybuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ApplyButton item info.
            /// </summary>
            [RepositoryItemInfo("c21d8c26-76a1-41b5-8769-249fa9848d53")]
            public virtual RepoItemInfo ApplyButtonInfo
            {
                get
                {
                    return _applybuttonInfo;
                }
            }

            /// <summary>
            /// The MachinesDataTable item.
            /// </summary>
            [RepositoryItem("12368075-a573-4c36-a0d5-944e5b805c72")]
            public virtual Ranorex.TableTag MachinesDataTable
            {
                get
                {
                    return _machinesdatatableInfo.CreateAdapter<Ranorex.TableTag>(true);
                }
            }

            /// <summary>
            /// The MachinesDataTable item info.
            /// </summary>
            [RepositoryItemInfo("12368075-a573-4c36-a0d5-944e5b805c72")]
            public virtual RepoItemInfo MachinesDataTableInfo
            {
                get
                {
                    return _machinesdatatableInfo;
                }
            }
        }

        /// <summary>
        /// The CertificatePageAppFolder folder.
        /// </summary>
        [RepositoryFolder("4463a818-cb8d-440d-8987-7a7c1dd007d0")]
        public partial class CertificatePageAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new certificatePage  folder.
            /// </summary>
            public CertificatePageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("certificatePage", "/dom[@domain='localhost:9291' and @caption='Privacy error']", parentFolder, 30000, null, true, "4463a818-cb8d-440d-8987-7a7c1dd007d0", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4463a818-cb8d-440d-8987-7a7c1dd007d0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4463a818-cb8d-440d-8987-7a7c1dd007d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The PrivacyErrorGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("af3b81c0-3113-4f1b-9d24-4215344fd6ca")]
        public partial class PrivacyErrorGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new PrivacyErrorGoogleChrome  folder.
            /// </summary>
            public PrivacyErrorGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PrivacyErrorGoogleChrome", "/form[@title~'^Privacy\\ error\\ -\\ Google\\ Ch']", parentFolder, 30000, null, true, "af3b81c0-3113-4f1b-9d24-4215344fd6ca", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "container[@accessiblename~'^Privacy\\ error\\ -\\ Google\\ Ch']/?/?/titlebar[@accessiblerole='TitleBar']", 30000, null, "0b6a44fd-d5be-458d-995e-cbbca6295d28");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("af3b81c0-3113-4f1b-9d24-4215344fd6ca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("af3b81c0-3113-4f1b-9d24-4215344fd6ca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("0b6a44fd-d5be-458d-995e-cbbca6295d28")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("0b6a44fd-d5be-458d-995e-cbbca6295d28")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}