///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SWA_1_6_5_Release_Specific_Test_cases
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Rough_Work recording.
    /// </summary>
    [TestModule("726eb067-681a-48df-9eb9-28c36b299151", ModuleType.Recording, 1)]
    public partial class Rough_Work : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SWA_1_6_5_Release_Specific_Test_casesRepository repository.
        /// </summary>
        public static SWA_1_6_5_Release_Specific_Test_casesRepository repo = SWA_1_6_5_Release_Specific_Test_casesRepository.Instance;

        static Rough_Work instance = new Rough_Work();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Rough_Work()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Rough_Work Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IderaDashboard.C8FQ30B' at 75;11.", repo.IderaDashboard.C8FQ30BInfo, new RecordItemIndex(0));
            repo.IderaDashboard.C8FQ30B.Click("75;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IderaDashboard.C8FQ70A' at 36;17.", repo.IderaDashboard.C8FQ70AInfo, new RecordItemIndex(1));
            repo.IderaDashboard.C8FQ70A.Click("36;17");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
